### ISSUE TITLE
Application gives exception when using the camera functionality

### ISSUE THREAD

**Issue by MZ2106644** [janschneiderou/PT2023#1]
I forked the project and tried to use both the 'Practice presentation' and 'practice sentences' modes which use the camera functionality (I'm using the built-in cam on my laptop). Visual Studio gave me an exception:
![Capture](https://user-images.githubusercontent.com/102732823/229185274-6bafbdc9-88a1-4505-90fe-aca1b1ce381d.PNG)
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=PT2023
  StackTrace:
   at PT2023.PoseNetEstimator.Inference(Mat inputImage) in C:\Users\Marlon\source\repos\PT2023\PT2023\PoseNetEstimator.cs:line 392
`
I hope you can resolve this issue.

**Comment by janschneiderou** [comment]
my guess would be that for some reason some of the dependencies got updated
and the updated versions do not work

**Comment by MZ2106644** [comment]
The unchanged project also had the same issue which is why I tried updating some the dependencies to see if that would do something to help solve this issue. I just reversed everything so that the code is unchanged again now. However I still get the same exception.

**Comment by MZ2106644** [comment]
I fixed the issue. I just had so set the "Platform target" to x64 in the build tab of Properties.
